const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.Anchor,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{ScrollTo: 0},
	{Player: 0},
	{TiledBackground: 0},
	{Solid: 0},
	{TiledBackground2: 0},
	{TiledBackground3: 0},
	{Text: 0},
	{Text2: 0},
	{TiledBackground4: 0},
	{Text3: 0},
	{playAgainbtn: 0},
	{TiledBackground5: 0},
	{deathGround: 0},
	{TiledBackground6: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{TiledBackground7: 0},
	{TiledBackground8: 0},
	{checkpoint: 0},
	{Sprite3: 0},
	{TiledBackground9: 0},
	{Lava: 0},
	{Text4: 0},
	{Text5: 0},
	{Anchor: 0},
	{ScoreLbl: 0},
	{CoinLbl: 0},
	{ScoreTxt: 0},
	{Coin: 0},
	{TiledBackground10: 0},
	{Spark: 0},
	{hurtDamage: 0},
	{TiledBackground11: 0},
	{Text6: 0},
	{Text7: 0},
	{Score: 0},
	{Score2: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Text3: class extends self.ITextInstance {},
	playAgainbtn: class extends self.IButtonInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	deathGround: class extends self.ITiledBackgroundInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	checkpoint: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	Lava: class extends self.ITiledBackgroundInstance {},
	Text4: class extends self.ITextInstance {},
	Text5: class extends self.ITextInstance {},
	ScoreLbl: class extends self.ITextInstance {},
	CoinLbl: class extends self.ISpriteInstance {},
	ScoreTxt: class extends self.ITextInstance {},
	Coin: class extends self.ISpriteInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	Spark: class extends self.ISpriteInstance {},
	hurtDamage: class extends self.ITiledBackgroundInstance {},
	TiledBackground11: class extends self.ITiledBackgroundInstance {},
	Text6: class extends self.ITextInstance {},
	Text7: class extends self.ITextInstance {}
}